### ISSUE TITLE
color picker recommendation?

### ISSUE THREAD

**Issue by mikenutt** [NCSU-Libraries/infographics#1]
I like Material Palette, but [ColorBrewer](http://colorbrewer2.org) is almost always my recommended color picker (evidence-based, proven in the field, color-blind options). Is the idea that Material Palette is simple to use? If anyone is sophisticated enough to implement a custom color palette in an infographic, perhaps they could handle a more sophisticated tool?

**Comment by HanRain** [comment]
I agree that ColorBrewer should be the preferred recommended tool. Should we add a separate section for basic design tools and list more than one color picker?

**Comment by ghost** [comment]
I'd say that any tool listed has to justify itself so that we don't just list things arbitrarily. So if we were to include another color picker besides our top choice (e.g., Material Palette or something else) we should provide a brief description of why we're mentioning it (e.g., easy to use, allows custom color palettes).

**Comment by ghost** [comment]
I took a stab at updating the readme. Feel free to revise.
